liip_imagine:
    driver: 'gd'
    filter_sets:
        cache: ~
        thumbnail:
            quality: 98
            filters:
                thumbnail: { size: [600, 400], mode: outbound }
        thumbnailbig:
            quality: 98
            filters:
                thumbnail: { size: [1200, 800] }